apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ping-pong-dep
  namespace: default
  labels:
    app:  ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  replicas: 1
  template:
    metadata:
      labels:
        app:  ping-pong
    spec:
      containers:
      - name:  ping-pong
        image:  kalmis-local-registry:2000/ping-pong:v0.5.1