apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: default
spec:
  selector:
    app: log-output
  type: NodePort
  ports:
  - name: log-output
    protocol: TCP
    port: 7999
    targetPort: 8000
    nodePort: 30080